### ISSUE TITLE
Document formatting tags

### ISSUE THREAD

**Issue by matysek** [openlyrics/openlyrics#27]
<a href="https://github.com/GoogleCodeExporter"><img src="https://avatars.githubusercontent.com/u/9614759?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [GoogleCodeExporter](https://github.com/GoogleCodeExporter)**
_Sunday Mar 29, 2015 at 21:00 GMT_
_Originally opened as https://github.com/matysek/openlyrics/issues/27_

---

Documentation needs to be updated.
See Issue #16 for more information.

Original issue reported on code.google.com by `s.mehrbrodt` on 20 May 2014 at 1:58

Tasks:
- RelaxNG: (no changes needed)
- [x] Documentation + Changelog
- [x] Reference implementation: XSL (CSS is impossible)
- 0.8 to 0.9 XSL converter (no changes needed)
- 0.9 to 0.8 XSL converter (no changes needed, it is in 0.8)

**Comment by gyuris** [comment]
Question for OpenLP developers:

- What is the difference between normal `<br>` element and `<tag name="br">` (break)? Why this default tag was created in OpenLP?
- What is the difference between `<lines>` element and `<tag name="p">` (paragraph)? Why this default tag was created OpenLP?

**Comment by gyuris** [comment]
Question are answered on IRC:

superfly: 
- OpenLP has formatting tags, and I think the <tag> was a way for OpenLyrics to support formatting tags so that they are not lost when exporting and importing songs between instances of OpenLP (or whatever other lyrics app you're using)
- so <br> is a regular line break, whereas <tag name="br"> is a tag named "br" (which may or may not be related to a <br> tag in HTML)
- {br} could be anything -- not even necessarily a line break, it could be Bold Red text
- "br" is just a name, it has no meaning beyond what a user has assigned to it
