### ISSUE TITLE
Validator doesn't work properly

### ISSUE THREAD

**Issue by matysek** [openlyrics/openlyrics#28]
<a href="https://github.com/GoogleCodeExporter"><img src="https://avatars.githubusercontent.com/u/9614759?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [GoogleCodeExporter](https://github.com/GoogleCodeExporter)**
_Sunday Mar 29, 2015 at 21:00 GMT_
_Originally opened as https://github.com/matysek/openlyrics/issues/28_

---

```
Change the verse name-attribute into something invalid like "fvccre", and it 
doesn't make any difference.
```

Original issue reported on code.google.com by `peterpas...@gmail.com` on 2 Mar 2015 at 3:59

**Comment by gyuris** [comment]
As I see "fvccre" is a valid token for verse@name because the RELAX NG scheme declares an another free token here: [/openlyrics-0.8.rng#L433](https://github.com/openlyrics/openlyrics/blob/d742be46f26492b9038a9508c2fc4ee9b94912b3/openlyrics-0.8.rng#L433)

This is maybe an [undocumented](https://docs.openlyrics.org/en/latest/dataformat.html#verse-name) feature. Or a bug.

To test:
- switch to single-source branch
- run `make validate`: should be all passed
- in some example file add "fvccre" for a verse name
- run `make validate`: it passed
- remove line 433 from `/openlyrics-0.8.rng`
- run `make validate`: it failed.

Devs, is it a feature or a bug? Can I remove line 433 from 0.9?

**Comment by gyuris** [comment]
Supporting free tokens is removed in single-source branch.
